version: '3'
services:
  nextcloud:
    image: nextcloud
    ports:
      - 80:80
    links:
      - mysql-next
    restart: always

  mysql-next:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Password
