version: '3'
services:
  owncloud:
    image: owncloud
    restart: always
    links:
      - mysql
    ports:
      - 8080:80

  mysql:
    image: mariadb
    restart: always
    ports:
      - 3308:3306
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: owncloud
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Password
